# Generated by Django 3.1.5 on 2021-01-25 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scavenger_hunt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='externallink',
            name='description',
            field=models.CharField(blank=True, help_text='Enter a description of the location.', max_length=2400),
        ),
        migrations.AlterField(
            model_name='image',
            name='title',
            field=models.CharField(default='Image', help_text='Optional. Enter descriptive text for the image', max_length=200),
        ),
        migrations.AlterField(
            model_name='pavemember',
            name='bio',
            field=models.CharField(blank=True, help_text='Enter a short bio of the member.', max_length=2400),
        ),
        migrations.AlterField(
            model_name='question',
            name='intro',
            field=models.CharField(blank=True, help_text='Enter the introduction text for this question/riddle.', max_length=2400),
        ),
        migrations.AlterField(
            model_name='questioninstance',
            name='directions',
            field=models.CharField(blank=True, help_text='Enter directions from the current location to the answer location.', max_length=2400),
        ),
    ]
