# Generated by Django 3.1.5 on 2021-07-31 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scavenger_hunt', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StartingInstance',
            new_name='AnnArborStartingInstance',
        ),
        migrations.CreateModel(
            name='CampusStartingInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='scavenger_hunt.location')),
            ],
        ),
    ]
