# Generated by Django 3.1.5 on 2021-07-31 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scavenger_hunt', '0002_auto_20210731_2110'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='choicequestion',
            options={'ordering': ['question', 'answer']},
        ),
        migrations.RenameField(
            model_name='choicequestion',
            old_name='correctAnswer',
            new_name='answer',
        ),
        migrations.AddField(
            model_name='choicequestion',
            name='answerFive',
            field=models.CharField(default='none', help_text='Enter the fifth answer choice for the question/riddle.', max_length=200),
            preserve_default=False,
        ),
    ]
