# Generated by Django 3.1.5 on 2021-01-26 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scavenger_hunt', '0002_auto_20210125_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externallink',
            name='description',
            field=models.TextField(blank=True, help_text='Enter a description of the location.'),
        ),
        migrations.AlterField(
            model_name='hint',
            name='hint',
            field=models.TextField(help_text='Enter the text for the hint.'),
        ),
        migrations.AlterField(
            model_name='location',
            name='description',
            field=models.TextField(blank=True, help_text="Enter a description of the location and it's significance."),
        ),
        migrations.AlterField(
            model_name='pavemember',
            name='bio',
            field=models.TextField(blank=True, help_text='Enter a short bio of the member.'),
        ),
        migrations.AlterField(
            model_name='question',
            name='intro',
            field=models.TextField(blank=True, help_text='Enter the introduction text for this question/riddle.'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.TextField(help_text='Enter the prompt for the question/riddle.'),
        ),
        migrations.AlterField(
            model_name='questioninstance',
            name='directions',
            field=models.TextField(blank=True, help_text='Enter directions from the current location to the answer location.'),
        ),
    ]
