# Generated by Django 3.1.5 on 2021-08-01 01:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scavenger_hunt', '0003_auto_20210731_2255'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(default='No additional information', help_text='Enter the description block for the home page')),
                ('instructions', models.TextField(default='No additional information', help_text='Enter the instructions block for the home page')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scavenger_hunt.image')),
            ],
        ),
    ]
