# Generated by Django 3.1.5 on 2021-01-30 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scavenger_hunt', '0004_extrapageabout'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='link',
            field=models.URLField(blank=True, help_text='Enter the target URL.'),
        ),
    ]
