# Generated by Django 3.1.5 on 2021-08-01 03:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scavenger_hunt', '0004_homepagecontent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annarborquestioninstance',
            name='choiceQuestion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scavenger_hunt.choicequestion'),
        ),
        migrations.AlterField(
            model_name='annarborquestioninstance',
            name='openQuestion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scavenger_hunt.openquestion'),
        ),
        migrations.AlterField(
            model_name='campusquestioninstance',
            name='choiceQuestion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scavenger_hunt.choicequestion'),
        ),
        migrations.AlterField(
            model_name='campusquestioninstance',
            name='openQuestion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scavenger_hunt.openquestion'),
        ),
    ]
