# Generated by Django 3.1.5 on 2021-01-31 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scavenger_hunt', '0005_location_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='externallink',
            name='photo',
            field=models.URLField(blank=True, help_text='Enter the target images hosted URL. Check the live site to make sure that the image was accessible.'),
        ),
    ]
