# Generated by Django 3.1.5 on 2021-08-01 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scavenger_hunt', '0005_auto_20210801_0310'),
    ]

    operations = [
        migrations.AddField(
            model_name='choicequestion',
            name='answerSix',
            field=models.CharField(blank=True, help_text='Enter the sixth answer choice for the question/riddle.', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='annarborquestioninstance',
            name='directions',
            field=models.TextField(blank=True, help_text='Enter directions from the current location to the answer location.', null=True),
        ),
        migrations.AlterField(
            model_name='campusquestioninstance',
            name='directions',
            field=models.TextField(blank=True, help_text='Enter directions from the current location to the answer location.', null=True),
        ),
        migrations.AlterField(
            model_name='choicequestion',
            name='album',
            field=models.ManyToManyField(blank=True, null=True, to='scavenger_hunt.Image'),
        ),
        migrations.AlterField(
            model_name='choicequestion',
            name='answerFive',
            field=models.CharField(blank=True, help_text='Enter the fifth answer choice for the question/riddle.', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='choicequestion',
            name='answerFour',
            field=models.CharField(blank=True, help_text='Enter the fourth answer choice for the question/riddle.', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='choicequestion',
            name='answerThree',
            field=models.CharField(blank=True, help_text='Enter the third answer choice for the question/riddle.', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='choicequestion',
            name='answerTwo',
            field=models.CharField(blank=True, help_text='Enter the second answer choice for the question/riddle.', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='choicequestion',
            name='hints',
            field=models.ManyToManyField(blank=True, null=True, to='scavenger_hunt.Hint'),
        ),
        migrations.AlterField(
            model_name='choicequestion',
            name='intro',
            field=models.TextField(blank=True, help_text='Enter the introduction text for this question/riddle.', null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='album',
            field=models.ManyToManyField(blank=True, null=True, to='scavenger_hunt.Image'),
        ),
        migrations.AlterField(
            model_name='location',
            name='description',
            field=models.TextField(blank=True, help_text="Enter a description of the location and it's significance.", null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='link',
            field=models.URLField(blank=True, help_text='Enter the target URL.', null=True),
        ),
        migrations.AlterField(
            model_name='openquestion',
            name='album',
            field=models.ManyToManyField(blank=True, null=True, to='scavenger_hunt.Image'),
        ),
        migrations.AlterField(
            model_name='openquestion',
            name='hints',
            field=models.ManyToManyField(blank=True, null=True, to='scavenger_hunt.Hint'),
        ),
        migrations.AlterField(
            model_name='openquestion',
            name='intro',
            field=models.TextField(blank=True, help_text='Enter the introduction text for this question/riddle.', null=True),
        ),
        migrations.AlterField(
            model_name='pavemember',
            name='bio',
            field=models.TextField(blank=True, help_text='Enter a short bio of the member.', null=True),
        ),
        migrations.AlterField(
            model_name='pavemember',
            name='email',
            field=models.EmailField(blank=True, help_text='Enter the members email for contact.', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='pavemember',
            name='link',
            field=models.URLField(blank=True, help_text='Enter the target images hosted URL. Check the live site to make sure that the image was accessible.', null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='aa_questions_completed',
            field=models.ManyToManyField(blank=True, null=True, to='scavenger_hunt.AnnArborQuestionInstance'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='campus_questions_completed',
            field=models.ManyToManyField(blank=True, null=True, to='scavenger_hunt.CampusQuestionInstance'),
        ),
    ]
