# Generated by Django 3.1.5 on 2021-08-01 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scavenger_hunt', '0006_auto_20210801_0349'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnArborConclusion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(default='No additional information', help_text='Enter the text block for the congratulations piece')),
            ],
        ),
        migrations.CreateModel(
            name='CampusConclusion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(default='No additional information', help_text='Enter the text block for the congratulations piece')),
            ],
        ),
        migrations.AlterField(
            model_name='choicequestion',
            name='album',
            field=models.ManyToManyField(blank=True, to='scavenger_hunt.Image'),
        ),
        migrations.AlterField(
            model_name='choicequestion',
            name='hints',
            field=models.ManyToManyField(blank=True, to='scavenger_hunt.Hint'),
        ),
        migrations.AlterField(
            model_name='location',
            name='album',
            field=models.ManyToManyField(blank=True, to='scavenger_hunt.Image'),
        ),
        migrations.AlterField(
            model_name='openquestion',
            name='album',
            field=models.ManyToManyField(blank=True, to='scavenger_hunt.Image'),
        ),
        migrations.AlterField(
            model_name='openquestion',
            name='hints',
            field=models.ManyToManyField(blank=True, to='scavenger_hunt.Hint'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='aa_questions_completed',
            field=models.ManyToManyField(blank=True, to='scavenger_hunt.AnnArborQuestionInstance'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='campus_questions_completed',
            field=models.ManyToManyField(blank=True, to='scavenger_hunt.CampusQuestionInstance'),
        ),
    ]
