# Generated by Django 3.1.5 on 2021-08-02 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scavenger_hunt', '0007_auto_20210801_2334'),
    ]

    operations = [
        migrations.AddField(
            model_name='annarborconclusion',
            name='link',
            field=models.URLField(blank=True, help_text='Enter the target images hosted URL. Check the live site to make sure that the image was accessible.', null=True),
        ),
        migrations.AddField(
            model_name='campusconclusion',
            name='link',
            field=models.URLField(blank=True, help_text='Enter the target images hosted URL. Check the live site to make sure that the image was accessible.', null=True),
        ),
    ]
