# Generated by Django 3.1.5 on 2021-08-02 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scavenger_hunt', '0008_auto_20210802_0155'),
    ]

    operations = [
        migrations.AddField(
            model_name='choicequestion',
            name='explanation',
            field=models.TextField(blank=True, help_text='Enter the explanation for the answer to this question/riddle.', null=True),
        ),
        migrations.AddField(
            model_name='openquestion',
            name='explanation',
            field=models.TextField(blank=True, help_text='Enter the explanation for the answer to this question/riddle.', null=True),
        ),
    ]
