# Generated by Django 3.1.5 on 2021-08-02 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scavenger_hunt', '0009_auto_20210802_1824'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampusExternalLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the text you want to appear with the hyperlink.', max_length=200)),
                ('link', models.URLField(help_text='Enter the target URL.')),
                ('photo', models.URLField(blank=True, help_text='Enter the target images hosted URL. Check the live site to make sure that the image was accessible.')),
                ('description', models.TextField(blank=True, help_text='Enter a description of the location.')),
            ],
        ),
        migrations.RenameModel(
            old_name='ExternalLink',
            new_name='AnnArborExternalLink',
        ),
    ]
